import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "@/lib/api";
import AppShell from "@/components/AppShell";
import PageHeader from "@/components/PageHeader";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Sparkles, Save, Play, Trash2, Loader2 } from "lucide-react";
import { toast } from "sonner";

const EXAMPLES = [
  "Buy NIFTY when 10-day SMA crosses above 30-day SMA. Exit on crossover down. 3% SL, 8% target.",
  "Mean-reversion on RELIANCE: enter long when RSI(14) < 30, exit when RSI > 60. 2% stop loss.",
  "Trend-follow BANKNIFTY using EMA 9 vs EMA 21. Stop loss 2.5%, target 7%.",
];

export default function StrategyBuilder() {
  const navigate = useNavigate();
  const [prompt, setPrompt] = useState(EXAMPLES[0]);
  const [generating, setGenerating] = useState(false);
  const [dsl, setDsl] = useState(null);
  const [name, setName] = useState("");
  const [items, setItems] = useState([]);

  const fetchList = async () => {
    const { data } = await api.get("/strategies");
    setItems(data.items);
  };

  useEffect(() => {
    fetchList();
  }, []);

  const generate = async () => {
    setGenerating(true);
    try {
      const { data } = await api.post("/strategies/generate", { prompt });
      setDsl(data.dsl);
      setName(data.dsl?.name || "Untitled");
      toast.success("Strategy generated by GPT-5.2");
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const save = async () => {
    if (!dsl) return;
    try {
      await api.post("/strategies", { name, description: dsl.description, dsl });
      toast.success("Strategy saved");
      setDsl(null);
      setName("");
      fetchList();
    } catch {
      toast.error("Save failed");
    }
  };

  const remove = async (id) => {
    try {
      await api.delete(`/strategies/${id}`);
      toast.success("Deleted");
      fetchList();
    } catch {
      toast.error("Delete failed");
    }
  };

  const runBacktest = (s) => {
    sessionStorage.setItem("af_backtest_dsl", JSON.stringify({ dsl: s.dsl, id: s.id, name: s.name }));
    navigate("/backtest");
  };

  return (
    <AppShell>
      <PageHeader
        overline="AI / Quant Engine"
        title="Strategy Builder"
        description="Describe the strategy in plain English. GPT-5.2 will convert it to an executable DSL ready to backtest or paper-trade."
      />

      <div className="p-8 grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Generator */}
        <div className="lg:col-span-3 panel p-6 space-y-5" data-testid="strategy-builder-panel">
          <div>
            <Label className="overline">Natural-language strategy</Label>
            <Textarea
              data-testid="strategy-prompt-input"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="mt-2 min-h-[110px] rounded-none bg-[var(--bg-page)] border-[var(--border)] font-mono-data text-sm"
              placeholder="Describe entry, exit, stops…"
            />
            <div className="flex flex-wrap gap-2 mt-3">
              {EXAMPLES.map((ex, i) => (
                <button
                  key={`ex-${ex.slice(0, 20)}`}
                  data-testid={`strategy-example-${i}`}
                  onClick={() => setPrompt(ex)}
                  className="text-xs px-2 py-1 border border-[var(--border)] hover:border-white txt-secondary hover:text-white transition-colors"
                >
                  Example {i + 1}
                </button>
              ))}
            </div>
          </div>

          <Button
            data-testid="strategy-generate-btn"
            onClick={generate}
            disabled={generating || !prompt.trim()}
            className="rounded-none bg-white text-black hover:bg-zinc-200 font-section tracking-wider h-11"
          >
            {generating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
            {generating ? "GENERATING WITH GPT-5.2…" : "GENERATE STRATEGY"}
          </Button>

          {dsl && (
            <div className="space-y-4 pt-4 section-rule">
              <div className="flex items-end gap-3">
                <div className="flex-1">
                  <Label className="overline">Strategy name</Label>
                  <Input
                    data-testid="strategy-name-input"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    className="mt-2 rounded-none bg-[var(--bg-page)] border-[var(--border)] font-mono-data"
                  />
                </div>
                <Button
                  data-testid="strategy-save-btn"
                  onClick={save}
                  className="rounded-none bg-white text-black hover:bg-zinc-200 font-section tracking-wider h-10"
                >
                  <Save className="w-4 h-4 mr-2" /> SAVE
                </Button>
              </div>
              <div>
                <div className="overline mb-2">DSL preview</div>
                <pre data-testid="strategy-dsl-preview" className="dsl-viewer bg-[var(--bg-page)] border border-[var(--border)] p-4 text-zinc-200">
{JSON.stringify(dsl, null, 2)}
                </pre>
              </div>
            </div>
          )}
        </div>

        {/* Saved list */}
        <div className="lg:col-span-2 panel p-6">
          <div className="overline mb-3">Your strategies · {items.length}</div>
          {items.length === 0 && (
            <div className="txt-muted text-sm">No strategies yet. Generate one to get started.</div>
          )}
          <div className="space-y-3">
            {items.map((s) => (
              <div key={s.id} className="border border-[var(--border)] p-4" data-testid={`strategy-item-${s.id}`}>
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="font-section text-sm truncate">{s.name}</div>
                    <div className="overline mt-1">{s.dsl?.symbol} · {s.dsl?.timeframe || "1d"}</div>
                    {s.description && (
                      <div className="text-xs txt-secondary mt-2 line-clamp-2">{s.description}</div>
                    )}
                  </div>
                  <div className="flex gap-1 shrink-0">
                    <Button
                      data-testid={`strategy-run-${s.id}`}
                      size="sm"
                      variant="ghost"
                      onClick={() => runBacktest(s)}
                      className="rounded-none h-8 px-2"
                    >
                      <Play className="w-3.5 h-3.5" />
                    </Button>
                    <Button
                      data-testid={`strategy-delete-${s.id}`}
                      size="sm"
                      variant="ghost"
                      onClick={() => remove(s.id)}
                      className="rounded-none h-8 px-2 hover:text-red-400"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </AppShell>
  );
}
